-
  idx: 1
  position:
  position:
    x: 5.0
    y: 2.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 1.0
    w: 0.0
-
  idx: 2
  position:
    x: 2.0
    y: 3.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
-
  idx: 3
  position:
  position:
    x: 6.0
    y: 4.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 1.0
    w: 0.0
-
  idx: 4
  position:
  position:
    x: 2.0
    y: 9.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 1.0
    w: 0.0
-
  idx: 5
  position:
  position:
    x: 9.0
    y: 2.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 1.0
    w: 0.0
-
  idx: 6
  position:
  position:
    x: 7.0
    y: 7.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 1.0
    w: 0.0
-
  idx: 7
  position:
  position:
    x: 5.0
    y: 7.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 1.0
    w: 0.0
-
  idx: 8
  position:
  position:
    x: 2.0
    y: 7.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 1.0
    w: 0.0
